import 'datatables.net/js/jquery.dataTables.js';
import 'datatables.net-bs/js/dataTables.bootstrap.js';
import 'datatables.net-buttons/js/dataTables.buttons.js';
import 'datatables.net-buttons/js/buttons.html5.js';
import 'datatables.net-buttons/js/buttons.flash.js';
import 'datatables.net-buttons/js/buttons.print.js';
import 'datatables.net-buttons-bs/js/buttons.bootstrap.js';
import 'datatables.net-responsive/js/dataTables.responsive.js';
import 'datatables.net-responsive-bs/js/responsive.bootstrap.js';
